version: 2.1
jobs:
  working_directory: ~/nest-graphql-best-practice
  build:
    docker:
      - image: circleci/node:12
        environment:
          ACCESS_TOKEN_SECRET: chnirt1803
    steps:
      - checkout
      - run: npm install
      - run: npm run gen
      - run: npm run start:prod
